server {
    listen 88;

    # Servir les fichiers React statiques
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # IMPORTANT pour React Router :
        # /projets -> renvoie index.html -> React Router prend le relais
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers le backend Express
    # "backend" = nom du service dans docker-compose.yml
    # Docker resout ce nom via son DNS interne
    location /api {
        proxy_pass http://backend:5000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 60s;
    }
}

